[build-system]
requires = ["setuptools-cuda-cpp", "flit_core >=3.2,<4", "wheel", "cython"]
build-backend = "flit_core.buildapi"

[project]
name = "culingam"
dependencies = ["numpy"]
dynamic = ["version", "description"]
